[tool.openhubble]
name = "OpenHubble CLI"
version = "1.5.3"
description = "OpenHubble Agent Debugger"
authors = ["OpenHubble Team <team@openhubble.com>"]

[tool.openhubble.dependencies]
python = ">=3.8"
